server:
  port: 8071

security:
  api_key: "NOT_USED"

oracle:
  soda:
    types:
      le_app:
        url: "https://ga8dd4d8f726db4-paralevelsdb0.adb.us-ashburn-1.oraclecloudapps.com/ords/paralevels_app/soda/latest/le_app_events"
        user: "PARALEVELS_APP"
        pass: "towsyd-joffir-3fogXi"
